//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notepad__.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEng() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notepad__.resources.ResourceEng", typeof(ResourceEng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our programms....
        ///bla-bla-bla
        ///
        ///made in the course for Microsoft Form
        ///				by Alex Zakharov.
        /// </summary>
        internal static string AboutBox {
            get {
                return ResourceManager.GetString("AboutBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutMenuItemString {
            get {
                return ResourceManager.GetString("AboutMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutName {
            get {
                return ResourceManager.GetString("AboutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentToolTips {
            get {
                return ResourceManager.GetString("CommentToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string EditCopyMenuItemString {
            get {
                return ResourceManager.GetString("EditCopyMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string EditCutMenuItemString {
            get {
                return ResourceManager.GetString("EditCutMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string EditDeleteMenuItemString {
            get {
                return ResourceManager.GetString("EditDeleteMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        internal static string EditDeselectMenuItemString {
            get {
                return ResourceManager.GetString("EditDeselectMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string EditFindMenuItemString {
            get {
                return ResourceManager.GetString("EditFindMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditMenuItemString {
            get {
                return ResourceManager.GetString("EditMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string EditPasteMenuItemString {
            get {
                return ResourceManager.GetString("EditPasteMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string EditRedoMenuItemString {
            get {
                return ResourceManager.GetString("EditRedoMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string EditReplaceMenuItemString {
            get {
                return ResourceManager.GetString("EditReplaceMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string EditSelectMenuItemString {
            get {
                return ResourceManager.GetString("EditSelectMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string EditUndoMenuItemString {
            get {
                return ResourceManager.GetString("EditUndoMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string FileCreateMenuItemString {
            get {
                return ResourceManager.GetString("FileCreateMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string FileExitMenuItemString {
            get {
                return ResourceManager.GetString("FileExitMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenuItemString {
            get {
                return ResourceManager.GetString("FileMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FileOpenMenuItemString {
            get {
                return ResourceManager.GetString("FileOpenMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string FileSaveAsMenuItemString {
            get {
                return ResourceManager.GetString("FileSaveAsMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FileSaveMenuItemString {
            get {
                return ResourceManager.GetString("FileSaveMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string FormatBackColorMenuItemString {
            get {
                return ResourceManager.GetString("FormatBackColorMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string FormatFontMenuItemString {
            get {
                return ResourceManager.GetString("FormatFontMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string FormatMenuItemString {
            get {
                return ResourceManager.GetString("FormatMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: {0}, position: {1}.
        /// </summary>
        internal static string FormatStatus {
            get {
                return ResourceManager.GetString("FormatStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Document.
        /// </summary>
        internal static string NewDocument {
            get {
                return ResourceManager.GetString("NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomment.
        /// </summary>
        internal static string UnCommentToolTips {
            get {
                return ResourceManager.GetString("UnCommentToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# sintax.
        /// </summary>
        internal static string ViewCMenuItemString {
            get {
                return ResourceManager.GetString("ViewCMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark scheme.
        /// </summary>
        internal static string ViewDarkSchemeMenuItemString {
            get {
                return ResourceManager.GetString("ViewDarkSchemeMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ViewEnglishMenuItemString {
            get {
                return ResourceManager.GetString("ViewEnglishMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewMenuItemString {
            get {
                return ResourceManager.GetString("ViewMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string ViewRussianMenuItemString {
            get {
                return ResourceManager.GetString("ViewRussianMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View status.
        /// </summary>
        internal static string ViewStatusMenuItemString {
            get {
                return ResourceManager.GetString("ViewStatusMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White scheme.
        /// </summary>
        internal static string ViewWhiteSchemeMenuItemString {
            get {
                return ResourceManager.GetString("ViewWhiteSchemeMenuItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word warp.
        /// </summary>
        internal static string ViewWordWarpMenuItemString {
            get {
                return ResourceManager.GetString("ViewWordWarpMenuItemString", resourceCulture);
            }
        }
    }
}
